//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DianZan
    {
        public int DianZanID { get; set; }
        public int YongHuID { get; set; }
        public int TieZiID { get; set; }
        public int ZhuangTai { get; set; }
    
        public virtual TieZi TieZi { get; set; }
        public virtual YongHu YongHu { get; set; }
    }
}
