//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuanZhuYongHu
    {
        public int GuanZhuYongHuID { get; set; }
        public int YongHuIDYI { get; set; }
        public int YongHuIDER { get; set; }
        public int GuangZhuZhuangTai { get; set; }
        public int HuiGuanZhuangTai { get; set; }
        public int LaiHeiZhuangTai { get; set; }
    
        public virtual YongHu YongHu { get; set; }
        public virtual YongHu YongHu1 { get; set; }
    }
}
