//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YouXiEntities : DbContext
    {
        public YouXiEntities()
            : base("name=YouXiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DianZan> DianZan { get; set; }
        public virtual DbSet<FanKui> FanKui { get; set; }
        public virtual DbSet<FengJinRiZhi> FengJinRiZhi { get; set; }
        public virtual DbSet<GuanZhuYongHu> GuanZhuYongHu { get; set; }
        public virtual DbSet<LiaoTianShi1> LiaoTianShi1 { get; set; }
        public virtual DbSet<LiaoTianShi2> LiaoTianShi2 { get; set; }
        public virtual DbSet<LiaoTianShi3> LiaoTianShi3 { get; set; }
        public virtual DbSet<TieZi> TieZi { get; set; }
        public virtual DbSet<TieZiXiaJiaRiZhi> TieZiXiaJiaRiZhi { get; set; }
        public virtual DbSet<TieziXiangXi> TieziXiangXi { get; set; }
        public virtual DbSet<XinXi> XinXi { get; set; }
        public virtual DbSet<YongHu> YongHu { get; set; }
        public virtual DbSet<ZhaoPian> ZhaoPian { get; set; }
        public virtual DbSet<ZhuPinglun> ZhuPinglun { get; set; }
        public virtual DbSet<ZiPinglun> ZiPinglun { get; set; }
    }
}
