//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieZi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TieZi()
        {
            this.DianZan = new HashSet<DianZan>();
            this.TieZiXiaJiaRiZhi = new HashSet<TieZiXiaJiaRiZhi>();
            this.TieziXiangXi = new HashSet<TieziXiangXi>();
            this.ZhaoPian = new HashSet<ZhaoPian>();
            this.ZhuPinglun = new HashSet<ZhuPinglun>();
            this.ZiPinglun = new HashSet<ZiPinglun>();
        }
    
        public int TieZiID { get; set; }
        public int YongHuID { get; set; }
        public string TieZiMing { get; set; }
        public System.DateTime FaBuShiJian { get; set; }
        public int ZhuangTai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DianZan> DianZan { get; set; }
        public virtual YongHu YongHu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TieZiXiaJiaRiZhi> TieZiXiaJiaRiZhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TieziXiangXi> TieziXiangXi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZhaoPian> ZhaoPian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZhuPinglun> ZhuPinglun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZiPinglun> ZiPinglun { get; set; }
    }
}
