//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YongHu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YongHu()
        {
            this.DianZan = new HashSet<DianZan>();
            this.FanKui = new HashSet<FanKui>();
            this.FengJinRiZhi = new HashSet<FengJinRiZhi>();
            this.GuanZhuYongHu = new HashSet<GuanZhuYongHu>();
            this.GuanZhuYongHu1 = new HashSet<GuanZhuYongHu>();
            this.LiaoTianShi1 = new HashSet<LiaoTianShi1>();
            this.LiaoTianShi2 = new HashSet<LiaoTianShi2>();
            this.LiaoTianShi3 = new HashSet<LiaoTianShi3>();
            this.TieZi = new HashSet<TieZi>();
            this.XinXi = new HashSet<XinXi>();
            this.XinXi1 = new HashSet<XinXi>();
            this.ZhuPinglun = new HashSet<ZhuPinglun>();
            this.ZiPinglun = new HashSet<ZiPinglun>();
        }
    
        public int YongHuID { get; set; }
        public string YongHuMing { get; set; }
        public string MiMaHaXi { get; set; }
        public string YanZhi { get; set; }
        public string YouXiang { get; set; }
        public int ZhuangTai { get; set; }
        public System.DateTime ChuangJianShiJian { get; set; }
        public string QuanXian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DianZan> DianZan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FanKui> FanKui { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FengJinRiZhi> FengJinRiZhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuanZhuYongHu> GuanZhuYongHu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuanZhuYongHu> GuanZhuYongHu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiaoTianShi1> LiaoTianShi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiaoTianShi2> LiaoTianShi2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiaoTianShi3> LiaoTianShi3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TieZi> TieZi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XinXi> XinXi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XinXi> XinXi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZhuPinglun> ZhuPinglun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZiPinglun> ZiPinglun { get; set; }
    }
}
